name: TAV Build

on:
  push:
    branches: [ "25.x" ]
  pull_request:
    branches: [ "25.x" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential \
            libtool \
            autotools-dev \
            automake \
            pkg-config \
            bsdmainutils \
            python3 \
            libevent-dev \
            libboost-system-dev \
            libboost-filesystem-dev \
            libboost-test-dev \
            libboost-thread-dev \
            libsqlite3-dev

      - name: Build TAV
        run: |
          ./autogen.sh
          ./configure --without-gui --disable-wallet
          make -j2

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tav-build
          path: |
            src/bitcoind
            src/bitcoin-cli
            src/bitcoin-tx
            src/bitcoin-util
